services:
  postgres:
    image: postgres:15-alpine
    container_name: travel_agency_postgres
    restart: always
    environment:
      POSTGRES_DB: travel_agency_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      postgres -c shared_preload_libraries=pg_stat_statements
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

# run `sqlc generate` after migrations
  flyway:
    image: flyway/flyway
    container_name: flyway_migrations
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - MIGRATION_VERSION=${MIGRATION_VERSION:-latest}
    command: >
      -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      -user=${POSTGRES_USER}
      -password=${POSTGRES_PASSWORD}
      -connectRetries=10
      -locations=filesystem:/flyway/sql
      -baselineOnMigrate=true
      -target=${MIGRATION_VERSION}
      migrate &&
    volumes:
      - ./migrations/flyway/sql:/flyway/sql
    healthcheck:
      test: [ "CMD", "flyway", "info" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  seeding:
    container_name: seeder
    build:
      context: .
      dockerfile: docker/seeding/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MIGRATION_VERSION: ${MIGRATION_VERSION}
      SEED_COUNT: ${SEED_COUNT:-100}
      APP_ENV: ${APP_ENV}
      ANALYST_NAMES: ${ANALYST_NAMES}
    command: [ "sh", "-c", 'if [ "$APP_ENV" = "dev" ]; then ./seeder; fi' ]

  db-load-simulation:
    container_name: db-load-simulation-simulation
    build:
      context: .
      dockerfile: docker/db-load-simulation/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      seeding:
        condition: service_completed_successfully
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_ENV: ${APP_ENV}
    ports:
      - "8080:8080"
    command: ["./load"]

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./internal/db-load-simulation:/etc/prometheus

  metrics-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: metrics-exporter
    environment:
      DATA_SOURCE_URI: "postgres:5432/${POSTGRES_DB}?sslmode=disable"
      DATA_SOURCE_USER: ${POSTGRES_USER}
      DATA_SOURCE_PASS: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "9187:9187"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana-data: