services:
  postgres:
    image: postgres:15-alpine
    container_name: travel_agency_postgres
    restart: always
    environment:
      POSTGRES_DB: travel_agency_db
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    container_name: flyway_migrations
    depends_on:
      - postgres
    environment:
      - MIGRATION_VERSION=${MIGRATION_VERSION:-latest}
    command: >
      -url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      -user=${POSTGRES_USER}
      -password=${POSTGRES_PASSWORD}
      -connectRetries=10
      -locations=filesystem:/flyway/sql
      -baselineOnMigrate=true
      -target=${MIGRATION_VERSION}
      migrate
    volumes:
      - ./flyway/sql:/flyway/sql

volumes:
  postgres_data: